import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PWAyrs',
  description: 'Generated by AYRS',
  manifest: '/manifest.json',
  icons: { apple: '/manifest/icon-192x192.png' },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title></title>
        {/* <!-- Google tag (gtag.js) --> */}
        <script async src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_ANALYTICS_ID}`}></script>
        <script
          dangerouslySetInnerHTML={{
            __html:`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());            
            gtag('config', '${process.env.NEXT_PUBLIC_ANALYTICS_ID}',{
                page_path: window.location.pathname,
              });
            `,
          }}
        >
        </script>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
